Um array é uma coleção de elementos de um tipo de dados. No NumPy, você pode criar arrays de várias maneiras.

Array de Números Sequenciais

# Seção 1: Conceitos Básicos do NumPy


## 1.1. Instalação e Importação


In [1]:
import numpy as np

## 1.2. Criando Arrays


In [3]:
# 1️⃣ Para criar um array com números de 1 a 10:

arr1 = np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
# 2️⃣ Crie um array de 5 zeros:

zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [6]:
# 3️⃣ Crie um array de 5 uns:

ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


## 1.3. Espaço Linear

In [19]:
# 4️⃣ Para criar um array com valores espaçados linearmente entre 0 e 50, use np.linspace:

arr2 = np.linspace(0,50)
print(arr2)
print("\n")
print(np.linspace(0, 50, 5))

[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]


[ 0.  12.5 25.  37.5 50. ]


## 1.4. Matriz Identidade

In [21]:
# 5️⃣ Uma matriz identidade é uma matriz quadrada com 1s na diagonal principal:

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 1.5. Indexação e Fatias

In [22]:
# 6️⃣ Acesse os três primeiros elementos:

arr4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr4[:3])

[0 1 2]


## 1.6. Operações Matemáticas

In [24]:
# 7️⃣ Eleve cada elemento ao quadrado:
arr5 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr5**2)


[ 0  1  4  9 16 25 36 49 64 81]


In [26]:
# 8️⃣ Some dois arrays:

arr6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr7 = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
print(arr6 + arr7)


[9 9 9 9 9 9 9 9 9 9]


## 1.7. Reshape

In [30]:
# 9️⃣ Mude o formato de um array unidimensional para uma matriz 3x3:

arr8 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped_arr = arr8.reshape(5, 2)
print(reshaped_arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## 1.8. Valores Aleatórios

In [39]:
arr9 = np.random.rand(10, 10)
arredondado_inteiro = np.round(arr9, decimals=2)
print(arredondado_inteiro*100)

[[ 75.   3.  13.  28.  55.  43.  17.  34.  31.  66.]
 [ 68.  20.  90.  47.  92.  88.  69.  84.   6.  38.]
 [ 69.  10.  84.  99.  17.  35.  18.  92.  78.  49.]
 [ 49.  34.  49.  69. 100.  58.   0.  56.  29.  88.]
 [ 22.  44.  84.  25.  43.  96.  92.  33.  56.  41.]
 [ 98.  46.  70.   6.  80.  87.  67.  48.  85.  25.]
 [ 63.  94.  88.  76.  28.   7.  30.  21.  82.  77.]
 [ 32.  44.  78.  56.  68.   1.  15.  26.  59.  89.]
 [ 22.  97.  43.  19.  20.  83.  42.  49.  88.  37.]
 [ 20.  45.  67.  93.  88.  31.  18.  65.  99.  10.]]


# Seção 2: Operações Avançadas com NumPy


## 2.1. Operações Element-wise

In [40]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
multiplied_array = array1 * array2
print(multiplied_array)

[ 4 10 18]


## 2.2. Estatísticas Básicas


In [41]:
# Calcule a soma, média, mediana, desvio padrão e variância:

array = np.array([1, 2, 3, 4, 5])
sum_array = np.sum(array)
mean_array = np.mean(array)
median_array = np.median(array)
std_dev = array.std()
variance = array.var()

print(f"Soma: {sum_array}")
print(f"Média: {mean_array}")
print(f"Mediana: {median_array}")
print(f"Desvio Padrão: {std_dev}")
print(f"Variância: {variance}")

Soma: 15
Média: 3.0
Mediana: 3.0
Desvio Padrão: 1.4142135623730951
Variância: 2.0


## 2.3. Concatenação de Arrays


In [42]:
# Concatene dois arrays:

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated_array = np.concatenate((array1, array2))
print(concatenated_array)

[1 2 3 4 5 6]


## 2.4. Encontrando Valores Específicos


In [46]:
# Encontre os índices de elementos maiores que 5:

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = np.where(array > 5)
print(indices)
print(type(indices))
print(array[indices])
print(type(array[indices]))

(array([5, 6, 7, 8]),)
<class 'tuple'>
[6 7 8 9]
<class 'numpy.ndarray'>
