## 🎓 **Aula sobre: Introdução ao NumPy**

 <br>

### 🧭 Sumário da Aula

| # | Sub-tópico                      | Tempo Estimado | Complexidade |
|---|---------------------------------|----------------|--------------|
| 1 | Ficha de Revisão Rápida         | ~1 min         | ⭐           |
| 2 | Mergulho Profundo               | ~15 min        | ⭐⭐⭐⭐       |
| 3 | Profundezas e Conexões          | ~3 min         | ⭐⭐         |
| 4 | 🚀 Ação e Verificação            | ~5 min         | ⭐⭐         |
| 5 | 🌊 Mergulhos Adicionais          | Opcional      | ⭐⭐⭐⭐      |

 <br>

---
 <br>


### 1. 🧠 Ficha de Revisão Rápida | (O Essencial)

 <br>

> *NumPy* é a biblioteca principal para **arrays** (ndarray) em Python, oferecendo **vetorização** (operações em blocos rápidos em C) e **broadcasting** (alinha arrays de formas diferentes sem repetições).


### 2. 🔬 Mergulho Profundo | (Os Detalhes)

 <br>

#### **🎯 O Conceito Central**  
O **ndarray** aloca valores do mesmo tipo (*dtype*) em um bloco contínuo de memória, acelerando cálculos. A *vetorização* delega operações em larga escala ao C, eliminando loops Python lentos. O *broadcasting* ajusta arrays menores para combinar com maiores, copiando apenas a visão, não os dados.

 <br>

#### **🔗 Analogia de Data Science**  
É como em uma planilha gigante: em vez de somar 10 célula por célula, NumPy soma toda a coluna de uma vez; e, ao precisar somar uma linha curta a cada linha longa, ele “estica” a linha curta automaticamente, sem duplicar cada valor.


### **💻 Exemplos de Mercado (Abrangentes)**

#### **Nível Simples: Criando Arrays**


In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.zeros((2,3))
c = np.arange(0, 10, 2)
print(a, b, c)


In [4]:
# Pratique seu código aqui!

import numpy as np

a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.arange(0, 10, 2)

print(f"{a}\n\n {b}\n\n {c}")


[1 2 3]

 [[0. 0. 0.]
 [0. 0. 0.]]

 [0 2 4 6 8]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  

  ```python
  # “Computador, carregue seu ajudante NumPy e chame-o de np.”  
  import numpy as np  

  # “‘np’, transforme [1,2,3] em um array e guarde em ‘a’.”  
  a = np.array([1, 2, 3])  

  # “‘np’, crie uma prateleira 2×3 cheia de zeros e chame de ‘b’.”  
  b = np.zeros((2,3))  

  # “‘np’, faça uma esteira que solta 0,2,4,6,8 e guarde em ‘c’.”  
  c = np.arange(0, 10, 2)  

  # “Mostre as três criações juntas.”  
  print(a, b, c)  
  ```

  **2) Tabela de Estados Intermediários:**  
````
  | Passo | Variável | Conteúdo                 | O que é?                          |
  |:-----:|:---------|:-------------------------|:----------------------------------|
  | 1     | `a`      | `[1, 2, 3]` (int64)      | Fila de 3 números inteiros        |
  | 2     | `b`      | `[[0.,0.,0.],[0.,0.,0.]]`| Prateleira 2×3 de zeros           |
  | 3     | `c`      | `[0,2,4,6,8]` (int64)    | Sequência de números pares        |
  | 4     | –        | imprime `a`, `b`, `c`    | Saída combinada no console        |
````
  **3) Diagrama Mental (A Analogia Central):**  
  Imagine três caixas de blocos:  
  - **Caixa A:** três blocos numerados 1,2,3.  
  - **Caixa B:** grade 2×3 com blocos marcados “0”.  
  - **Caixa C:** esteira soltando blocos 0,2,4,6,8.  

  O `print()` é uma fotografia que exibe as três caixas lado a lado.

* **Cenário de Mercado:**  
  - **O que são “features”?** São pistas numéricas que descrevem dados, como idade, avaliação ou tempo de uso.  
  - **Por que inicializar?** Em um sistema de recomendação (ex: Netflix), criamos uma tabela vazia de zeros com `np.zeros((10000,15))` para armazenar pontuações previstas de 10.000 usuários e 15 features.  
  - **Ganho:** Alocar tudo de uma vez é como construir a estrutura inteira de um prédio de LEGO em segundos, em vez de montar tijolo por tijolo — é milhões de vezes mais rápido e economiza memória.

* **Boas Práticas:**  
  - **Afirmação:** “Especifique `dtype`, por ex., `float32`.”  
    - **Porquê:** Usar 32 bits em vez de 64 bits por número economiza **50%** de memória.  
    - **Analogia:** É como usar caixinhas menores para guardar brinquedos — você cabe o dobro no mesmo espaço.  
    - **Termo:** *`dtype`* é o “tamanho da caixinha” que guarda cada número; *float32* é um número decimal que usa 32 bits.


#### **Nível Intermediário: Operações Vetorizadas e Broadcasting**


In [ ]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
y = np.array([10,20,30])
soma = x + y
prod = x * 2
print(soma, prod)


In [8]:
# Pratique seu código aqui!

import numpy as np

x = np.array([[1, 2, 3,], [4, 5, 6]])
y = np.array([10, 20, 30])
soma = x + y
prod = x * 2

print(f"{soma}\n\n {prod}")

[[11 22 33]
 [14 25 36]]

 [[ 2  4  6]
 [ 8 10 12]]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  

  ```python
  # “NumPy, crie uma matriz 2×3.”  
  x = np.array([[1,2,3],[4,5,6]])  

  # “Crie um vetor de 3 números para ajustar.”  
  y = np.array([10,20,30])  

  # “Some y a cada linha de x de uma vez.”  
  soma = x + y  

  # “Multiplique cada elemento de x por 2.”  
  prod = x * 2  

  # “Mostre as matrizes resultantes.”  
  print(soma, prod)  
  ```

  **2) Tabela de Estados Intermediários:**  
````
  | Passo | Expressão | Resultado                         | O que representa?                   |
  |:-----:|:----------|:----------------------------------|:------------------------------------|
  | 1     | `x`       | `[[1,2,3],[4,5,6]]`               | Matriz de entrada                   |
  | 2     | `y`       | `[10,20,30]`                      | Vetor de bias                       |
  | 3     | `soma`    | `[[11,22,33],[14,25,36]]`         | Soma de bias                        |
  | 4     | `prod`    | `[[2,4,6],[8,10,12]]`             | Escala por 2                        |
  | 5     | –         | imprime `soma` e `prod`           | Saída final                         |
````
  **3) Diagrama Mental (A Analogia Central):**  
  Pense em um tabuleiro de jogo com duas linhas de slots; `y` são fichas de bônus que são “espalhadas” sob cada linha em um só movimento.

* **Cenário de Mercado:**  
  - **Por que usar broadcasting:** Ao treinar uma rede neural, adicionamos um vetor de **bias** a cada saída de camada. Broadcasting faz isso em um único passo, acelerando o treinamento e reduzindo linhas de código.  
  - **Exemplo real:** No TensorFlow, `outputs = inputs @ weights + bias` aplica broadcasting para somar `bias` sem laços.

* **Boas Práticas:**  
  - **Afirmação:** “Verifique shapes antes de operar.”  
    - **Porquê:** Evita erros de dimensão que quebram pipelines em produção.  
    - **Analogia:** É como conferir que as peças de LEGO possuem o encaixe correto antes de montar.


#### **Nível Avançado: Indexação e Fatiamento Avançado**


In [ ]:
import numpy as np
m = np.arange(16).reshape(4,4)
sub = m[1:3, [0,2]]
mask = (m % 2) == 0
pares = m[mask]
print(sub, pares)


In [15]:
# Pratique seu código aqui!

import numpy as np

m = np.arange(16).reshape(4, 4)
sub = m[1:3, [0,2]]
mask = (m%2) == 0
pares = m[mask]

print(m)
print("\n")
print(sub)
print("\n")
print(f"{mask}\n\n {pares}")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[ 4  6]
 [ 8 10]]


[[ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]]

 [ 0  2  4  6  8 10 12 14]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  

  ```python
  # “Gere uma grade 4×4 de 0 a 15.”  
  m = np.arange(16).reshape(4,4)  

  # “Extraia linhas 2–3 e colunas 1 e 3.”  
  sub = m[1:3, [0,2]]  

  # “Marque pares na grade.”  
  mask = (m % 2) == 0  

  # “Reúna todos os pares em um array.”  
  pares = m[mask]  

  # “Exiba submatriz e lista de pares.”  
  print(sub, pares)  
  ```

  **2) Tabela de Estados Intermediários:**  
  ````
  | Passo | Expressão | Conteúdo                            | O que é?                         |
  |:-----:|:----------|:------------------------------------|:---------------------------------|
  | 1     | `m`       | 4×4 de 0–15                        | Matriz original                  |
  | 2     | `sub`     | `[[4,6],[8,10]]`                   | Bloco central extraído           |
  | 3     | `mask`    | Booleano 4×4                       | True para casas pares            |
  | 4     | `pares`   | `[0,2,4,6,8,10,12,14]`             | Array linear de todos os pares   |
  | 5     | –         | imprime `sub` e `pares`            | Saída final                      |
````
  **3) Diagrama Mental (A Analogia Central):**  
  É como em um tabuleiro: pinta as células pares de verde e depois enfileira esses verdes num trenzinho, ao mesmo tempo em que recorta um retângulo central para estudo.

* **Cenário de Mercado:**  
  - **Por que filtrar por critério:** Em IoT, sensores enviam dados constantes. Filtrar valores pares (ou fora de padrão) reduz ruído.  
  - **Exemplo real:** Num centro de coleta de dados meteorológicos, selecionamos submatrizes de horários específicos e sensores-chave para prever tempestades.

* **Boas Práticas:**  
  - **Afirmação:** “Use máscaras booleanas para filtrar.”  
    - **Porquê:** Processamento ocorre em C, muito mais rápido que loops Python.  
    - **Analogia:** É como usar um filtro de cor para isolar só as peças verdes num vidro colorido.


#### **Nível DEUS (1/3): Operações Estatísticas Rápidas**


In [ ]:
import numpy as np
data = np.random.randn(1000, 5)
media = data.mean(axis=0)
desvio = data.std(axis=0)
print(media, desvio)


In [19]:
# Pratique seu código aqui!

import numpy as np

data = np.random.randn(1000,5)
media = data.mean(axis=0)
desvio = data.std(axis=0)

print(data)
print("\n")
print(media)
print("\n")
print(desvio)




[[-0.54539201 -0.26342499  0.55650263  0.83625561  0.71597904]
 [ 0.19749386  0.29244147 -1.08498    -0.7824382   0.43122872]
 [ 0.26002609 -1.62807857  0.29884787  0.33690403 -1.19668445]
 ...
 [-1.29054865  0.47617817  0.00938583  2.25328498 -1.19077638]
 [-0.01130432 -0.67695493 -0.22143187 -1.11494753 -2.60981396]
 [ 0.34981715 -0.85409693  0.03170622  1.23428602 -1.57196205]]


[ 0.06711527 -0.0159683  -0.02039246  0.00142528  0.01779817]


[1.01383342 0.97777369 1.02192127 0.99410675 1.02633472]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  

  ```python
  # “Crie 1000×5 valores aleatórios com distribuição normal.”  
  data = np.random.randn(1000, 5)  

  # “Calcule a média de cada coluna.”  
  media = data.mean(axis=0)  

  # “Calcule o desvio padrão de cada coluna.”  
  desvio = data.std(axis=0)  

  # “Mostre as médias e desvios.”  
  print(media, desvio)  
  ```

  **2) Tabela de Estados Intermediários:**  
```
  | Passo | Expressão   | Resultado                  | O que representa?                |
  |:-----:|:------------|:---------------------------|:---------------------------------|
  | 1     | `data`      | 1000×5 de floats           | Conjunto de dados brutos         |
  | 2     | `media`     | vetor length-5              | Valores médios por coluna        |
  | 3     | `desvio`    | vetor length-5              | Dispersão de cada coluna         |
  | 4     | –           | imprime `media` e `desvio` | Saída final                      |
```
  **3) Diagrama Mental (A Analogia Central):**  
  Pense em 5 baldes cheios de bolinhas coloridas: cada balde é uma coluna. A média é o “tamanho médio” das bolinhas e o desvio é o “quão diferentes” elas são umas das outras.

* **Cenário de Mercado:**  
  - **Por que calcular estatísticas:** Antes de treinar modelos, exploramos dados para entender distribuição e detectar outliers.  
  - **Exemplo real:** Em fintech, analisamos uma matriz de transações para cada tipo (5 colunas) e verificamos médias e desvios para detectar fraudes.

* **Boas Práticas:**  
  - **Afirmação:** “Use `axis=0` ou `axis=1` corretamente.”  
    - **Porquê:** Define se cálculos são feitos por coluna (`axis=0`) ou linha (`axis=1`).  
    - **Analogia:** É como escolher se você soma fileiras de prateleiras horizontais ou colunas verticais numa biblioteca.


#### **Nível DEUS (2/3): Álgebra Linear com NumPy**


In [ ]:
import numpy as np
A = np.array([[1,2],[3,4]])
b = np.array([5,6])
x = np.linalg.solve(A, b)
print(x)


In [20]:
# Pratique seu código aqui!

import numpy as np
A = np.array([[1,2],[3,4]])
b = np.array([5,6])
x = np.linalg.solve(A,b)
print(x)


[-4.   4.5]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  

  ```python
  # “Crie matriz 2×2 de coeficientes.”  
  A = np.array([[1,2],[3,4]])  

  # “Crie vetor de constantes.”  
  b = np.array([5,6])  

  # “Resolva o sistema Ax=b.”  
  x = np.linalg.solve(A, b)  

  # “Mostre a solução.”  
  print(x)  
  ```

  **2) Tabela de Estados Intermediários:**  
```
  | Passo | Expressão | Resultado         | O que faz?                         |
  |:-----:|:----------|:------------------|:-----------------------------------|
  | 1     | `A`       | `[[1,2],[3,4]]`   | Coeficientes do sistema            |
  | 2     | `b`       | `[5,6]`           | Termos constantes                  |
  | 3     | `x`       | `[-4, 4.5]`       | Solução do sistema                 |
  | 4     | –         | imprime `x`       | Saída final                        |
```

  **3) Diagrama Mental (A Analogia Central):**  
  É como equilibrar duas balanças simultâneas: encontrar pesos (`x`) que façam ambas as balanças ficarem niveladas.

* **Cenário de Mercado:**  
  - **Por que usar álgebra linear:** Em regressão linear, resolvemos sistemas para ajustar parâmetros que melhor preveem resultados.  
  - **Exemplo real:** Em atuação de precificação de seguro, ajustamos um modelo linear para prever riscos com base em variáveis.

* **Boas Práticas:**  
  - **Afirmação:** “Verifique se `det(A) != 0`.”  
    - **Porquê:** Uma matriz singular não tem solução única.  
    - **Analogia:** É como tentar resolver equações com peças faltando — não há resposta clara.


#### **Nível DEUS (3/3): Manipulação de Shape e Transposição**


In [ ]:
import numpy as np
arr = np.arange(8)
resh = arr.reshape(2,4)
transp = resh.T
print(resh, transp)


In [23]:
# Pratique seu código aqui!

import numpy as np

arr = np.arange(8)
resh = arr.reshape(2,4)
transp = resh.T

print(f"{arr}\n\n {resh}\n\n {transp}")

[0 1 2 3 4 5 6 7]

 [[0 1 2 3]
 [4 5 6 7]]

 [[0 4]
 [1 5]
 [2 6]
 [3 7]]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  

  ```python
  # “Crie vetor 0–7.”  
  arr = np.arange(8)  

  # “Transforme em matriz 2×4.”  
  resh = arr.reshape(2,4)  

  # “Troque linhas por colunas.”  
  transp = resh.T  

  # “Mostre original e transposto.”  
  print(resh, transp)  
  ```

  **2) Tabela de Estados Intermediários:**  
```
  | Passo | Expressão | Resultado                  | O que faz?                       |
  |:-----:|:----------|:---------------------------|:---------------------------------|
  | 1     | `arr`     | `[0,1,2,3,4,5,6,7]`        | Vetor original                  |
  | 2     | `resh`    | `[[0,1,2,3],[4,5,6,7]]`    | Matriz 2×4                     |
  | 3     | `transp`  | `[[0,4],[1,5],[2,6],[3,7]]`| Matriz 4×2 transposta         |
  | 4     | –         | imprime `resh` e `transp`  | Saída final                     |
```

  **3) Diagrama Mental (A Analogia Central):**  
  Imagine uma folha 2×4 de quadrados; transpor é girar essa folha, virando 2 linhas em 2 colunas.

* **Cenário de Mercado:**  
  - **Por que reshape/transposição:** Ao preparar dados para bibliotecas, às vezes precisamos trocar linhas por colunas para ajustar a entrada.  
  - **Exemplo real:** Em visão computacional, imagens são matrizes e, ao ajustar canais de cor, usamos transposição para reorganizar dimensões.

* **Boas Práticas:**  
  - **Afirmação:** “Use `.copy()` se precisar do array original.”  
    - **Porquê:** Algumas operações retornam **views** que compartilham memória; alterar uma altera a outra.  
    - **Analogia:** É como ter duas plantas no mesmo vaso — regar uma afeta a outra.


### 3. 🕸️ Profundezas e Conexões

 <br>

NumPy sustenta **pandas**, **scipy**, **scikit-learn** e frameworks de deep learning (TensorFlow, PyTorch). Compreender vetorização e broadcasting é essencial para escrever código eficiente e escalar análises a milhões de pontos de dados.

 <br>

---

 <br>


### 4. 🚀 Ação e Verificação

 <br>

#### **🤔 Desafio Prático**
1. Crie um array de 20 valores igualmente espaçados entre 0 e 1.  
2. Gere uma matriz 3×3 de valores aleatórios e normalize cada linha (soma = 1).  
3. Utilize máscara booleana para substituir valores negativos por zero em um array 4×4.  
4. Resolva um sistema 3×3 linear com `np.linalg.solve`.  
5. Transponha um tensor 3D invertendo as duas últimas dimensões.

 <br>

#### **❓ Pergunta de Verificação**
Por que vetorização e broadcasting são preferíveis a loops Python, e como o *layout de memória* (C-contíguo vs Fortran-contíguo) pode afetar a performance?

 <br>

---

 <br>
