## 🎓 **Aula sobre: Criação de Vetores e Arrays em NumPy**

 <br>

### 🧭 Sumário da Aula

| # | Sub-tópico                      | Tempo Estimado | Complexidade |
|---|---------------------------------|----------------|--------------|
| 1 | Ficha de Revisão Rápida         | ~1 min         | ⭐           |
| 2 | Mergulho Profundo               | ~15 min        | ⭐⭐⭐⭐       |
| 3 | Profundezas e Conexões          | ~3 min         | ⭐⭐         |
| 4 | 🚀 Ação e Verificação            | ~5 min         | ⭐⭐         |
| 5 | 🌊 Mergulhos Adicionais          | Opcional      | ⭐⭐⭐⭐      |

 <br>

---
 <br>


### 1. 🧠 Ficha de Revisão Rápida | (O Essencial)

 <br>

> Em NumPy, criamos **arrays** (ndarray) a partir de listas, sequências ou funções de geração.  
> Arrays guardam dados do mesmo *dtype* em blocos contínuos, acelerando cálculos e otimizando memória.


### 2. 🔬 Mergulho Profundo | (Os Detalhes)

 <br>

#### **🎯 O Conceito Central**  
Um **array** em NumPy é uma grade de valores do mesmo tipo, armazenados em um bloco contíguo de memória.  
- `np.array()` converte listas/tuplas em arrays.  
- `np.zeros()`, `np.ones()`, `np.empty()`, `np.full()` criam arrays preenchidos sem precisar de listas Python.  
- `np.arange()`, `np.linspace()` geram sequências numéricas automaticamente.

 <br>

#### **🔗 Analogia de Data Science**  
Pense em fichas de dados: em vez de anotar uma a uma, você máquina imprime centenas de fichas formatadas num cartucho de uma só vez. Isso é mais rápido e evita erros manuais.


### **💻 Exemplos de Mercado (Abrangentes)**

#### **Nível Simples: Criando Arrays Básicos**


In [ ]:
import numpy as np
a = np.array([5, 6, 7])
z = np.zeros(4)
o = np.ones(3)
print(a, z, o)


In [2]:
# Pratique seu código aqui!

import numpy as np
a = np.array([5, 6, 7])
z = np.zeros(4)
o = np.ones(3)

print(f"a: {a}\n")
print(f"z: {z}\n")
print(f"o: {o}\n")


a: [5 6 7]

z: [0. 0. 0. 0.]

o: [1. 1. 1.]



* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  

  ```python
  # “Computador, transforme [5,6,7] num array e chame de ‘a’.”  
  a = np.array([5, 6, 7])  

  # “‘np’, crie uma fila de 4 zeros e chame de ‘z’.”  
  z = np.zeros(4)  

  # “‘np’, crie uma fila de 3 uns e chame de ‘o’.”  
  o = np.ones(3)  

  # “Mostre as três filas.”  
  print(a, z, o)  
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Variável | Conteúdo       | O que é?                |
  |:-----:|:---------|:---------------|:------------------------|
  | 1     | `a`      | `[5,6,7]`      | Array de 3 inteiros     |
  | 2     | `z`      | `[0.,0.,0.,0.]`| Array de 4 zeros float  |
  | 3     | `o`      | `[1.,1.,1.]`   | Array de 3 uns float    |
  | 4     | –        | imprime `a,z,o`| Saída combinada         |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  Imagine três linhas de pedrinhas:  
  - Linha **A** com pedrinhas 5,6,7.  
  - Linha **Z** toda preta (zeros).  
  - Linha **O** toda branca (uns).  
  O `print()` é um farol que ilumina as três fileiras de pedrinhas.

* **Cenário de Mercado:**  
  - **O que são “features”?** São características numéricas de um conjunto de dados, como temperatura, vendas ou cliques.  
  - **Por que criar arrays básicos?** Em análises iniciais, você monta matrizes vazias (`zeros`) para coletar estatísticas, e matrizes de `ones` para máscaras, sem depender de listas que crescem dinamicamente.  
  - **Ganho:** Alocar um array de zeros de 1 000 000 de pontos de uma vez leva milissegundos, enquanto inserir um milhão de itens em lista Python leva segundos e fragmenta a memória.

* **Boas Práticas:**  
  - **Afirmação:** “Prefira funções de geração (`zeros`, `ones`) a loops.”  
    - **Porquê:** Essas funções chamam código C otimizado que preenche blocos de memória muito mais rápido.  
    - **Analogia:** É como usar uma máquina de carimbar 100 formulários em segundos em vez de escrever à mão.  
    - **Termo:** *`dtype`* define o “tamanho da caixinha” de cada número; `float64` (64 bits) armazena maior precisão, mas `float32` (32 bits) economiza memória quando a precisão extra não é necessária.


#### **Nível Intermediário: Sequências Numéricas**


In [ ]:
import numpy as np
r1 = np.arange(0, 20, 5)
r2 = np.linspace(0, 1, num=5)
f = np.full((2,4), fill_value=7)
print(r1, r2, f)


In [3]:
# Pratique seu código aqui!

import numpy as np

r1 = np.arange(0, 20, 5)
r2 = np.linspace(0, 1, num=5)
f = np.full((2,4), fill_value = 7)

print(f"r1: {r1}\n")
print(f"r2: {r2}\n")
print(f"f: {f}\n")


r1: [ 0  5 10 15]

r2: [0.   0.25 0.5  0.75 1.  ]

f: [[7 7 7 7]
 [7 7 7 7]]



* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  

  ```python
  # “Crie [0,5,10,15] e chame de ‘r1’.”  
  r1 = np.arange(0, 20, 5)  

  # “Crie 5 números igualmente espaçados entre 0 e 1.”  
  r2 = np.linspace(0, 1, num=5)  

  # “Crie 2×4 onde cada posição vale 7.”  
  f = np.full((2,4), fill_value=7)  

  # “Mostre r1, r2 e f.”  
  print(r1, r2, f)  
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão                  | Resultado               | O que representa?            |
  |:-----:|:---------------------------|:------------------------|:-----------------------------|
  | 1     | `r1`                       | `[ 0, 5,10,15]`         | Range com passo 5            |
  | 2     | `r2`                       | `[0.,0.25,0.5,0.75,1.]` | Linspace de 5 pontos         |
  | 3     | `f`                        | `[[7,7,7,7],[7,7,7,7]]` | Matriz cheia de 7            |
  | 4     | –                          | imprime `r1,r2,f`       | Saída final                  |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  Imagine uma régua (arange) marcando saltos de 5, e uma escada (linspace) dividindo o degrau em 5 partes iguais; e um bloco de 2×4 onde cada célula é um pedacinho pintado de “7”.

* **Cenário de Mercado:**  
  - Em engenharia de dados, usamos `arange` para indexar lotes em intervals, e `linspace` para criar gráficos ou pontos de interpolação.  
  - **Exemplo real:** Num projeto de simulação, `linspace` gera 1000 instantes de tempo para analisar a evolução de uma variável.

* **Boas Práticas:**  
  - **Afirmação:** “Escolha `linspace` quando precisar de contagem exata de pontos.”  
    - **Porquê:** Garante distribuição uniforme e exatidão no número de elementos, ao contrário de `arange`, que pode não incluir o fim esperado por causa de precisão flutuante.  
    - **Analogia:** É como dividir um bolo em fatias iguais; `linspace` corta exatas 8 fatias, `arange` dependerá do tamanho do bolo e da faca.


#### **Nível Avançado: Multidimensionalidade e Aleatoriedade**


In [ ]:
import numpy as np
m = np.arange(27).reshape(3,3,3)
rand = np.random.rand(2,5)
print(m, rand)


In [4]:
# Pratique seu código aqui!

import numpy as np

m = np.arange(27).reshape(3, 3, 3)
rand = np.random.rand(2, 5)

print(f"m: {m}\n")
print(f"rand: {rand}\n")


m: [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

rand: [[0.95833215 0.51742782 0.09035784 0.36078871 0.5865723 ]
 [0.90627973 0.78409248 0.62389851 0.76009562 0.90283095]]



* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  

  ```python
  # “Crie números 0–26 e forme 3×3×3 cubo.”  
  m = np.arange(27).reshape(3,3,3)  

  # “Gere 2×5 de números aleatórios entre 0 e 1.”  
  rand = np.random.rand(2,5)  

  # “Mostre cubo e matriz randômica.”  
  print(m, rand)  
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão                 | Resultado                         | O que é?                    |
  |:-----:|:--------------------------|:----------------------------------|:----------------------------|
  | 1     | `m`                       | 3×3×3 cubo de 0–26                | Array tridimensional        |
  | 2     | `rand`                    | 2×5 de floats aleatórios          | Matriz de amostra aleatória |
  | 3     | –                         | imprime `m` e `rand`              | Saída final                 |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  Imagine um cubo mágico 3×3×3 preenchido com números sequenciais e, ao lado, um retângulo 2×5 cujas células são gotas de chuva de valores entre 0 e 1.

* **Cenário de Mercado:**  
  - Em visão computacional, usamos arrays 3D para representar imagens coloridas (altura×largura×canais).  
  - **Exemplo real:** Ao treinar uma rede GAN, você alimenta um tensor 3D de ruído (`rand`) para gerar novas imagens.

* **Boas Práticas:**  
  - **Afirmação:** “Prefira `np.random.default_rng()` em vez de `np.random.rand()`.”  
    - **Porquê:** O novo gerador é mais robusto e oferece métodos mais seguros e reprodutíveis.  
    - **Analogia:** É como usar uma fonte mais confiável de água potável para garantir que cada gole seja seguro.


### 3. 🕸️ Profundezas e Conexões

 <br>

Arrays NumPy são a base para **pandas** (DataFrames derivam de ndarrays), **scikit-learn** (espera vetores/matrizes), e frameworks de deep learning (tensors estendem arrays). Entender formas e tipos é essencial para pipelines eficientes.

 <br>

---

 <br>


### 4. 🚀 Ação e Verificação

 <br>

#### **🤔 Desafio Prático**
1. Crie um vetor de 50 números de 0 a 1 com `linspace`.  
2. Monte um cubo 4×4×4 com `arange` e `reshape`.  
3. Gere uma matriz de zeros do mesmo formato de um array dado usando `np.zeros_like()`.  
4. Crie uma matriz aleatória 3×3 com distribuição normal (`randn`).  
5. Compare `np.random.rand()` e `np.random.default_rng()` em reprodutibilidade.

 <br>

#### **❓ Pergunta de Verificação**
Por que é crucial entender o *dtype* e o *shape* ao criar arrays, e como isso impacta velocidade e uso de memória?

 <br>

---
 <br>
