## 🎓 **Aula sobre: Indexação e Fatiamento de Arrays NumPy**

<br>

### 🧭 Sumário da Aula

| # | Sub-tópico                       | Tempo Estimado | Complexidade |
|---|----------------------------------|----------------|--------------|
| 1 | Ficha de Revisão Rápida          | ~1 min         | ⭐           |
| 2 | Mergulho Profundo                | ~15 min        | ⭐⭐⭐⭐       |
| 3 | Profundezas e Conexões           | ~3 min         | ⭐⭐         |
| 4 | 🚀 Ação e Verificação             | ~5 min         | ⭐⭐         |
| 5 | 🌊 Mergulhos Adicionais Opcionais | Opcional      | ⭐⭐⭐⭐      |

<br>

---
<br>


### 1. 🧠 Ficha de Revisão Rápida | (O Essencial)

<br>

> - **Indexação simples:** `arr[i]` ou `arr[i,j]` acessa elementos.  
> - **Fatiamento:** `arr[start:stop:step]` retorna subarrays.  
> - **Máscaras booleanas:** `arr[arr > x]` filtra valores.  
> - **Fancy indexing:** seleção arbitrária via lista ou array de índices.

<br>


### 2. 🔬 Mergulho Profundo | (Os Detalhes)

<br>

#### **🎯 O Conceito Central**  
Indexação e fatiamento são formas de “apontar” para partes de um `ndarray`. Máscaras booleanas marcam elementos por condição, e *fancy indexing* usa listas de posições. Tudo executado em C, sem loops Python, garantindo alta performance.

<br>

#### **🔗 Analogia de Data Science**  
Imagine um mural de 1000×1000 pixels.  
- Com indexação você escolhe um pixel específico.  
- Com fatiamento recorta um bloco retangular.  
- Com máscara destaca apenas pixels brilhantes.  
- Com fancy indexing seleciona pixels espalhados em qualquer padrão.

<br>

### **💻 Exemplos de Mercado (Abrangentes)**


#### **Nível Simples: Indexação e Fatiamento Básico**


In [ ]:
import numpy as np
arr = np.arange(10)       # [0,1,2,...,9]
print(arr[2])             # 2
print(arr[3:7])           # [3 4 5 6]
print(arr[:5])            # [0 1 2 3 4]
print(arr[::2])           # [0 2 4 6 8]


In [11]:
# Pratique seu código aqui!
import numpy as np

arr = np.arange(10)

print("1) ", arr)
print("2) ", arr[2])
print("3) ", arr[3:7])
print("4) ", arr[:5])
print("5) ", arr[5:])
print("6) ", arr[::2])
print("7) ", arr[1::2])
print("8) ", arr[::-1])

1)  [0 1 2 3 4 5 6 7 8 9]
2)  2
3)  [3 4 5 6]
4)  [0 1 2 3 4]
5)  [5 6 7 8 9]
6)  [0 2 4 6 8]
7)  [1 3 5 7 9]
8)  [9 8 7 6 5 4 3 2 1 0]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie um array de 0 a 9.”  
  arr = np.arange(10)

  # “Pegue o valor na posição 2.”  
  print(arr[2])

  # “Recorte do índice 3 até antes de 7.”  
  print(arr[3:7])

  # “Pegue os 5 primeiros elementos.”  
  print(arr[:5])

  # “Pegue cada segundo elemento.”  
  print(arr[::2])
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão   | Saída         | O que é?                  |
  |:-----:|:------------|:--------------|:--------------------------|
  | 1     | `arr`       | `[0…9]`       | Array de 10 elementos     |
  | 2     | `arr[2]`    | `2`           | Elemento único            |
  | 3     | `arr[3:7]`  | `[3,4,5,6]`   | Subarray contínuo         |
  | 4     | `arr[:5]`   | `[0,1,2,3,4]` | Início implícito          |
  | 5     | `arr[::2]`  | `[0,2,4,6,8]` | Passo 2                   |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  Imagine uma fileira de 10 cadeiras numeradas; indexação é sentar em uma específica, fatiamento é reservar um bloco contíguo, pular de 2 em 2 é alternar assentos.

* **Cenário de Mercado:**  
  Em **séries temporais**, usar `data[-30:]` retorna uma *view* com os últimos 30 dias, permitindo cálculos de média móvel sem duplicar dados.

* **Boas Práticas:**  
  - **Afirmação:** “Use fatiamento para criar *views*, não cópias.”  
    - **Porquê:** Economiza memória e evita overhead de cópia.  
    - **Analogia:** É como olhar por uma janela em vez de tirar uma foto da paisagem.


#### **Nível Intermediário: Acesso a Linhas e Colunas**


In [ ]:
import numpy as np
mat = np.arange(1,17).reshape(4,4)
print(mat[1])        # segunda linha inteira
print(mat[:,2])      # terceira coluna inteira
print(mat[::2, ::3]) # linhas de 2 em 2 e colunas de 3 em 3


In [30]:
# Pratique seu código aqui!

import numpy as np

mat = np.arange(1, 17).reshape(4,4)

print(mat)
print("\n")
print("1)", mat[1])
print("\n")
print("2)", mat[:,2])
print("\n")
print("3)", mat[::2,::3])
print("\n")
print("4)", mat[:3,1:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


1) [5 6 7 8]


2) [ 3  7 11 15]


3) [[ 1  4]
 [ 9 12]]


4) [[ 2  3]
 [ 6  7]
 [10 11]]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie matriz 4×4 de 1 a 16.”  
  mat = np.arange(1,17).reshape(4,4)

  # “Pegue a segunda linha inteira.”  
  print(mat[1])

  # “Pegue a terceira coluna inteira.”  
  print(mat[:,2])

  # “Pegue linhas 0 e 2, colunas 0 e 3.”  
  print(mat[::2, ::3])
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão     | Saída                | O que faz?                      |
  |:-----:|:--------------|:---------------------|:--------------------------------|
  | 1     | `mat[1]`      | `[5,6,7,8]`          | Linha de índice 1               |
  | 2     | `mat[:,2]`    | `[3,7,11,15]`        | Coluna de índice 2              |
  | 3     | `mat[::2,::3]`| `[[1,4],[9,12]]`     | Linhas e colunas com salto      |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  É como selecionar fileiras e colunas numa planilha para gerar relatórios específicos.


#### **Nível Avançado: Máscaras Booleanas e Fancy Indexing**


In [ ]:
import numpy as np
mat = np.arange(1,17).reshape(4,4)
mask = (mat % 2 == 0)
print(mat[mask])          # pares
idx = [0,2]
print(mat[idx, idx])      # diagonal fancy
print(mat[[1,3],[2,0]])   # seleção arbitrária


In [41]:
# Pratique seu código aqui!

import numpy as np
mat = np.arange(1,17).reshape(4,4)
mask = (mat % 2 == 0)
idx = [0,2]

print(mat)
print("\n")
print("1)", mat[mask])
print("\n")
print("2)", mat[idx, idx])
print("\n")
print("3)",mat[[1,3], [2,0]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


1) [ 2  4  6  8 10 12 14 16]


2) [ 1 11]


3) [ 7 13]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie matriz 4×4 de 1 a 16.”  
  mat = np.arange(1,17).reshape(4,4)

  # “Marque valores pares.”  
  mask = (mat % 2 == 0)

  # “Filtre pares.”  
  print(mat[mask])

  # “Selecione diagonal fancy.”  
  idx = [0,2]
  print(mat[idx, idx])

  # “Selecione posições (1,2) e (3,0).”  
  print(mat[[1,3],[2,0]])
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão           | Saída             | O que faz?                   |
  |:-----:|:--------------------|:------------------|:-----------------------------|
  | 1     | `mat[mask]`         | `[2,4,…,16]`      | Vetor de pares               |
  | 2     | `mat[idx, idx]`     | `[1,11]`          | Diagonal fancy               |
  | 3     | `mat[[1,3],[2,0]]`  | `[6,13]`          | Seleção arbitrária           |
  | 4     | –                   | imprime tudo      | Saída final                  |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  Máscara é peneira que deixa passar só peças pares; fancy indexing é lista de coordenadas exatas.


#### **Nível DEUS (1/3): Seleção com `np.take`**


In [ ]:
import numpy as np
arr = np.arange(20)
sel = np.take(arr, [2,5,7,9])
print(sel)


In [42]:
# Pratique seu código aqui!

import numpy as np
arr = np.arange(20)
sel = np.take(arr, [2,5,7,9])
print(sel)



[2 5 7 9]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie array 0–19.”  
  arr = np.arange(20)

  # “Pegue itens nos índices [2,5,7,9].”  
  sel = np.take(arr, [2,5,7,9])

  # “Mostre seleção.”  
  print(sel)
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão              | Saída       | O que faz?                |
  |:-----:|:-----------------------|:-----------|:--------------------------|
  | 1     | `arr`                  | `[0…19]`   | Array original            |
  | 2     | `np.take(arr, [...])`  | `[2,5,7,9]`| Seleção por lista         |
  | 3     | –                      | imprime     | Saída final               |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  É como seguir uma lista de compras numeradas num corredor de números.


#### **Nível DEUS (2/3): Ellipsis e `np.newaxis`**


In [ ]:
import numpy as np
A = np.arange(8).reshape(2,2,2)
print(A[...,1])
B = A[:, np.newaxis, :]
print(B.shape)


In [50]:
# Pratique seu código aqui!

import numpy as np

a = np.arange(8).reshape(2,2,2)

print(a)
print("\n")

print(a[...,1])

b = a[:, np.newaxis, :]

print("\n")
print(b.shape)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[[1 3]
 [5 7]]


(2, 1, 2, 2)


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie tensor 2×2×2.”  
  A = np.arange(8).reshape(2,2,2)

  # “Pegue índice 1 em última dimensão.”  
  print(A[...,1])

  # “Insira dimensão de batch.”  
  B = A[:, np.newaxis, :]
  print(B.shape)
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão           | Saída        | O que faz?                          |
  |:-----:|:--------------------|:-------------|:------------------------------------|
  | 1     | `A[...,1]`          | 2×2          | Fatiamento em última dimensão       |
  | 2     | `A[:,np.newaxis,:]` | (2,1,2,2)    | Insere dimensão extra               |
  | 3     | –                   | imprime      | Saída final                         |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  Ellipsis “…” é “pegue tudo antes”; `newaxis` é “abra mais espaço” para batch.


#### **Nível DEUS (3/3): Combinação Avançada**


In [ ]:
import numpy as np
data = np.arange(24).reshape(4,6)
mask = (data % 3 == 0)
idx = np.where(mask)
result = data[idx].reshape(2,2,1)
print(result)


In [57]:
# Pratique seu código aqui!

import numpy as np
data = np.arange(24).reshape(4,6)
mask = (data % 3 == 0)

print(data)
print("\n")
print(mask)
print("\n")

idx = np.where(mask)
print(idx)
print("\n")

result = data[idx].reshape(2,2,2)
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[[ True False False  True False False]
 [ True False False  True False False]
 [ True False False  True False False]
 [ True False False  True False False]]


(array([0, 0, 1, 1, 2, 2, 3, 3]), array([0, 3, 0, 3, 0, 3, 0, 3]))


[[[ 0  3]
  [ 6  9]]

 [[12 15]
  [18 21]]]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie 4×6.”  
  data = np.arange(24).reshape(4,6)

  # “Marque múltiplos de 3.”  
  mask = (data % 3 == 0)

  # “Encontre índices.”  
  idx = np.where(mask)

  # “Selecione e reshape 2×2×1.”  
  result = data[idx].reshape(2,2,2)

  # “Mostre resultado.”  
  print(result)
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão      | Saída      | O que faz?                     |
  |:-----:|:---------------|:-----------|:-------------------------------|
  | 1     | `mask`         | Booleano   | True para múltiplos de 3       |
  | 2     | `idx`          | coords     | Índices dos múltiplos          |
  | 3     | `result`       | 2×2×2      | Tensor recriado                |
  | 4     | –              | imprime    | Saída final                    |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  É como mapear quadrados vermelhos num tabuleiro e remontar mini-tabuleiros para análise.


### 3. 🕸️ Profundezas e Conexões

<br>

Indexação e fatiamento alimentam **pandas**, **PyTorch** e **OpenCV**, tornando possível pipelines escaláveis e interativas.

<br>

---
<br>


### 4. 🚀 Ação e Verificação

<br>

#### **🤔 Desafio Prático**
1. Dado `arr = np.arange(25).reshape(5,5)`, extraia a terceira coluna inteira.  
2. Filtre `arr` por múltiplos de 4.  
3. Use fancy indexing para pegar (0,4), (2,2) e (4,0).  
4. Subarray linhas 1–3, colunas 2–4.  
5. Máscara + reshape para criar tensor 2×2×1 de pares.

<br>

#### **❓ Pergunta de Verificação**
Como *view* vs *copy* afeta memória e mutabilidade ao fatiar arrays?

<br>

---
<br>
