## 🎓 **Aula sobre: Operações com NumPy Arrays**

<br>

### 🧭 Sumário da Aula

| # | Sub-tópico                       | Tempo Estimado | Complexidade |
|---|----------------------------------|----------------|--------------|
| 1 | Ficha de Revisão Rápida          | ~1 min         | ⭐           |
| 2 | Mergulho Profundo                | ~15 min        | ⭐⭐⭐⭐       |
| 3 | Profundezas e Conexões           | ~3 min         | ⭐⭐         |
| 4 | 🚀 Ação e Verificação             | ~5 min         | ⭐⭐         |
| 5 | 🌊 Mergulhos Adicionais Opcionais | Opcional      | ⭐⭐⭐⭐      |

<br>

---
<br>


### 1. 🧠 Ficha de Revisão Rápida | (O Essencial)

<br>

> - **Ufuncs (funções universais):** operações vetorizadas sobre arrays, ex: `np.add`, `np.multiply`.  
> - **Reduções:** agregam valores, ex: `sum()`, `max()`, `min()`.  
> - **Acumulações:** acumulam resultados em cada etapa, ex: `cumsum()`, `cumprod()`.  
> - **Produto escalar e outer:** multiplicações matriciais e extensões de ufuncs em combinação de arrays.

<br>


### 2. 🔬 Mergulho Profundo | (Os Detalhes)

<br>

#### **🎯 O Conceito Central**  
As **ufuncs** são funções em C que operam elemento a elemento sem loops Python. As **reduções** resumem um array em valor único ou vetores por eixo. As **acumulações** geram um array de mesmos tamanhos com resultados parciais. O **produto escalar** (`@` ou `np.dot`) e o **outer** (`np.multiply.outer`) permitem operações de álgebra linear e combinação completa de vetores.

<br>

#### **🔗 Analogia de Data Science**  
Imagine um canteiro de plantio:  
- Ufuncs são ferramentas que regam todas as plantas de uma vez.  
- Reduções são colheitas que somam todos os frutos.  
- Acumulações são observações diárias do crescimento acumulado.  
- Produto escalar é como pesar contrapartes de duas colheitas e comparar resultados.  
- Outer é como cruzar cada tipo de semente com cada tipo de fertilizante para ver todas as combinações.

<br>

### **💻 Exemplos de Mercado (Abrangentes)**


#### **Nível Simples: Soma e Multiplicação Elemento a Elemento**


In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum_ab = a + b
prod_ab = a * b
print(sum_ab, prod_ab)


In [1]:
# Pratique seu código aqui!

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum_ab = a + b
prod_ab = a * b

print(sum_ab, prod_ab)

[5 7 9] [ 4 10 18]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie array [1,2,3].”  
  a = np.array([1, 2, 3])

  # “Crie array [4,5,6].”  
  b = np.array([4, 5, 6])

  # “Some elemento a elemento.”  
  sum_ab = a + b

  # “Multiplique elemento a elemento.”  
  prod_ab = a * b

  # “Mostre soma e produto.”  
  print(sum_ab, prod_ab)
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão     | Saída         | O que é?                       |
  |:-----:|:--------------|:--------------|:-------------------------------|
  | 1     | `a`           | `[1,2,3]`     | Primeiro array                 |
  | 2     | `b`           | `[4,5,6]`     | Segundo array                  |
  | 3     | `sum_ab`      | `[5,7,9]`     | Soma elemento a elemento       |
  | 4     | `prod_ab`     | `[4,10,18]`   | Produto elemento a elemento    |
  | 5     | –             | imprime       | Saída final                    |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  Pense em duas fileiras de baldes: um com [1,2,3], outro com [4,5,6]. A soma emparelha e derrama a combinação; a multiplicação emparelha e multiplica o conteúdo de cada par.

* **Cenário de Mercado:**  
  - **Por que usar operações elementares:** Em processamento de imagens, adicionar ou misturar canais RGB pixel a pixel é rotina.  
  - **Exemplo real:** Em filtros de imagem, `output = image + overlay` ajusta brilho e contraste de cada pixel simultaneamente.

* **Boas Práticas:**  
  - **Afirmação:** “Prefira ufuncs (+, *, np.add, np.multiply).”  
    - **Porquê:** Executadas em C, são **milhares de vezes** mais rápidas que loops Python.  
    - **Analogia:** É como regar todas as plantas de uma estufa com um canhão de água em vez de regadores manuais.


#### **Nível Intermediário: Reduções e Acumulações**


In [ ]:
import numpy as np
m = np.arange(12).reshape(3,4)
col_sum = m.sum(axis=0)
row_mean = m.mean(axis=1)
cumsum = m.cumsum(axis=1)
print(col_sum, row_mean, cumsum)


In [5]:
# Pratique seu código aqui!

import numpy as np

m = np.arange(12).reshape(3,4)

col_sum = m.sum(axis=0)
row_mean = m.mean(axis=1)
cumsum = m.cumsum(axis=1)

print(m)
print("\n")
print(col_sum)
print("\n")
print(row_mean)
print("\n")
print(cumsum)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[12 15 18 21]


[1.5 5.5 9.5]


[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie matriz 3×4 com valores 0–11.”  
  m = np.arange(12).reshape(3,4)

  # “Some cada coluna.”  
  col_sum = m.sum(axis=0)

  # “Calcule a média de cada linha.”  
  row_mean = m.mean(axis=1)

  # “Acumule soma em cada linha.”  
  cumsum = m.cumsum(axis=1)

  # “Mostre resultados.”  
  print(col_sum, row_mean, cumsum)
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo      | Expressão     | Saída                                | O que faz?                   |
  |:----------:|:--------------|:------------------------------------|:-----------------------------|
  | 1          | `m`           | 3×4 de 0–11                          | Matriz original              |
  | 2          | `col_sum`     | `[12,15,18,21]`                     | Soma de cada coluna          |
  | 3          | `row_mean`    | `[1.5,5.5,9.5]`                     | Média de cada linha          |
  | 4          | `cumsum`      | `[[0,1,3,6],[4,9,15,22],[8,17,27,38]]` | Soma acumulada por linha |
  | 5          | –             | imprime                              | Saída final                  |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  Imagine uma mesa com fileiras de moedas. A redução coleta todas as moedas por coluna ou calcula a média por linha. A acumulação empilha as moedas sucessivamente ao longo da linha.

* **Cenário de Mercado:**  
  - **Por que usar reduções e acumulações:** Em análise financeira, somar transações por dia (colunas) e acompanhar saldo acumulado (cumsum) é essencial para fluxo de caixa.  

* **Boas Práticas:**  
  - **Afirmação:** “Use `axis` corretamente.”  
    - **Porquê:** Define dimensão de agregação; `axis=0` afeta colunas, `axis=1` afeta linhas.  
    - **Analogia:** É como escolher se você soma produtos por coluna de prateleira ou por fileira de caixa.


#### **Nível Avançado: Produto Escalar e Outer**


In [ ]:
import numpy as np
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
dot = v1 @ v2
outer = np.multiply.outer(v1, v2)
print(dot, outer)


In [6]:
# Pratique seu código aqui!

import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

dot = v1 @ v2
outer = np.multiply.outer(v1, v2)

print(dot)
print("\n")
print(outer)

32


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie vetor [1,2,3].”  
  v1 = np.array([1,2,3])

  # “Crie vetor [4,5,6].”  
  v2 = np.array([4,5,6])

  # “Calcule produto escalar.”  
  dot = v1 @ v2

  # “Calcule produto outer (todas combinações).”  
  outer = np.multiply.outer(v1, v2)

  # “Mostre resultados.”  
  print(dot, outer)
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão                  | Saída                  | O que faz?                          |
  |:-----:|:---------------------------|:-----------------------|:------------------------------------|
  | 1     | `v1`                       | `[1,2,3]`              | Primeiro vetor                      |
  | 2     | `v2`                       | `[4,5,6]`              | Segundo vetor                       |
  | 3     | `dot`                      | `32`                   | Soma dos produtos correspondentes    |
  | 4     | `outer`                    | Matriz 3×3             | Combinações multiplicativas completas|
  | 5     | –                          | imprime                | Saída final                         |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  Produto escalar é como comparar listas de compras e somar custos pareados; outer é experimentar cada item da lista A com cada item da lista B.

* **Cenário de Mercado:**  
  - **Por que usar dot e outer:** Em recomendação, dot entre vetores de features mede similaridade; outer combina parâmetros de modelo e inputs para análise de sensibilidade.  

* **Boas Práticas:**  
  - **Afirmação:** “Use `@` para dot e `outer` para combinações.”  
    - **Porquê:** Sintaxe clara e performance otimizada por BLAS/C.  
    - **Analogia:** É como usar ferramentas especializadas: martelo para pregos, furadeira para parafusos.


#### **Nível DEUS (1/3): Ufuncs Personalizadas e Reduções Avançadas**


In [ ]:
import numpy as np
data = np.random.randint(1,100, size=(5,5))
prod = np.prod(data, axis=1)
max_min = np.max(data, axis=0) - np.min(data, axis=0)
print(prod, max_min)


In [7]:
# Pratique seu código aqui!

import numpy as np
data = np.random.randint(1,100, size=(5,5))
prod = np.prod(data, axis=1)
max_min = np.max(data, axis=0) - np.min(data, axis=0)
print(prod, max_min)


[39501000  7750080 36337500 12577488 46516464] [97 74 42 64 36]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Gere matriz 5×5 de inteiros aleatórios 1–99.”  
  data = np.random.randint(1,100, size=(5,5))

  # “Multiplique elementos de cada linha.”  
  prod = np.prod(data, axis=1)

  # “Calcule diferença entre max e min de cada coluna.”  
  max_min = np.max(data, axis=0) - np.min(data, axis=0)

  # “Mostre produto e variação.”  
  print(prod, max_min)
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo  | Expressão          | Saída              | O que faz?                     |
  |:------:|:-------------------|:-------------------|:-------------------------------|
  | 1      | `data`             | 5×5 int            | Matriz de entrada              |
  | 2      | `prod`             | vetor length-5     | Produto de cada linha          |
  | 3      | `max_min`          | vetor length-5     | Diferença max-min por coluna   |
  | 4      | –                  | imprime            | Saída final                    |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  Pense em cinco hastes de contas; cada haste multiplica suas contas, e colunas medem amplitude entre a conta maior e menor.

* **Cenário de Mercado:**  
  - **Por que usar funções de produto e range:** Em análise de risco, calcula-se produto de probabilidades por evento e variação de métricas entre sensores.  

* **Boas Práticas:**  
  - **Afirmação:** “Use `axis` para dimensão correta.”  
    - **Porquê:** Evita agregações indesejadas.  
    - **Analogia:** É como escolher se você agrupa produtos por prateleira ou por corredor.


#### **Nível DEUS (2/3): Acumulações e Ufuncs de Nível Técnico**


In [ ]:
import numpy as np
v = np.arange(1,6)
cumsum = np.add.accumulate(v)
cumprod = np.multiply.accumulate(v)
print(cumsum, cumprod)


In [8]:
# Pratique seu código aqui!

import numpy as np
v = np.arange(1,6)
print(v)
cumsum = np.add.accumulate(v)
cumprod = np.multiply.accumulate(v)
print("\n")
print(cumsum)
print("\n")
print(cumprod)

[1 2 3 4 5]


[ 1  3  6 10 15]


[  1   2   6  24 120]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie vetor 1–5.”  
  v = np.arange(1,6)

  # “Acumule soma.”  
  cumsum = np.add.accumulate(v)

  # “Acumule produto.”  
  cumprod = np.multiply.accumulate(v)

  # “Mostre resultados.”  
  print(cumsum, cumprod)
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo   | Expressão             | Saída             | O que faz?                  |
  |:-------:|:----------------------|:------------------|:----------------------------|
  | 1       | `v`                   | `[1,2,3,4,5]`     | Vetor original              |
  | 2       | `cumsum`              | `[1,3,6,10,15]`   | Soma acumulada              |
  | 3       | `cumprod`             | `[1,2,6,24,120]`  | Produto acumulado           |
  | 4       | –                     | imprime           | Saída final                 |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  É como anotar passo a passo o total acumulado e o produto acumulado de receitas diárias.

* **Cenário de Mercado:**  
  - **Por que usar accumulates:** Em simulações financeiras, acumulamos rendimentos diários para entender crescimento ao longo do tempo.  

* **Boas Práticas:**  
  - **Afirmação:** “Escolha ufuncs vs métodos de alto nível.”  
    - **Porquê:** Métodos específicos (`accumulate`) oferecem performance e controle de eixos.  
    - **Analogia:** É como usar receita passo a passo ou um pacote pronto de misturas.


#### **Nível DEUS (3/3): Combinações com Outer e Meshgrid**


In [ ]:
import numpy as np
x = np.arange(1,5)
y = np.arange(1,4)
grid = np.multiply.outer(x, y)
print(grid)


In [9]:
# Pratique seu código aqui!

import numpy as np
x = np.arange(1,5)
y = np.arange(1,4)
print(x)
print("\n")
print(y)
print("\n")
print(np.multiply.outer(x, y))


[1 2 3 4]


[1 2 3]


[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]


* **O que o código faz:**  

  **1) Explicação Linha a Linha (Diálogo com o Código):**  
  ```python
  # “Crie vetor 1–4.”  
  x = np.arange(1,5)

  # “Crie vetor 1–3.”  
  y = np.arange(1,4)

  # “Calcule todas as multiplicações cruzadas.”  
  grid = np.multiply.outer(x, y)

  # “Mostre a grade resultante.”  
  print(grid)
  ```

  **2) Tabela de Estados Intermediários:**

  ```markdown
  | Passo | Expressão             | Saída            | O que faz?                        |
  |:-----:|:----------------------|:-----------------|:----------------------------------|
  | 1     | `x`                   | `[1,2,3,4]`      | Primeiro vetor                    |
  | 2     | `y`                   | `[1,2,3]`        | Segundo vetor                     |
  | 3     | `grid`                | 4×3 matriz       | Combinação completa multiplicada  |
  | 4     | –                     | imprime          | Saída final                       |
  ```

  **3) Diagrama Mental (A Analogia Central):**  
  É como montar todos os pares possíveis de camisas e calças de um armário, gerando uma tabela completa de combinações.

* **Cenário de Mercado:**  
  - **Por que usar outer:** Em otimização de hiperparâmetros, testamos todas combinações de parâmetros para encontrar a melhor configuração.  

* **Boas Práticas:**  
  - **Afirmação:** “Use `outer` para grids de pesquisa.”  
    - **Porquê:** Evita loops aninhados e traz consistência de dados.  
    - **Analogia:** É como usar uma planilha para enumerar combinações em vez de anotar manualmente.


### 3. 🕸️ Profundezas e Conexões

<br>

Operações com arrays NumPy sustentam **pandas**, **scikit-learn** e frameworks de deep learning. Dominar ufuncs, reduções e produtos é vital para performance em modelos de machine learning e análises científicas.

<br>

---
<br>


### 4. 🚀 Ação e Verificação

<br>

#### **🤔 Desafio Prático**
1. Dado `arr = np.random.randint(1,20,size=(4,4))`, compute soma total, média por linha e vetor de máximos por coluna.  
2. Crie vetor `v = np.linspace(0,1,6)` e calcule `np.add.accumulate(v)`.  
3. Resolva produto escalar e outer para vetores `[1,0,1]` e `[2,3,4]`.  
4. Use `np.where` para substituir valores pares de `arr` por `-1`.  
5. Gere grade 5×5 com `np.multiply.outer` de vetores `1–5` e `6–10`.

<br>

#### **❓ Pergunta de Verificação**
Por que ufuncs e reduções superam loops Python e como o alinhamento de memória (C-contíguo vs Fortran-contíguo) influencia a performance?

<br>

---
<br>


### **Resposta Rápida**

**Ufuncs** e **reduções** (como `sum`, `mean`) superam loops em Python porque operam direto em **nível C**, com execução **vetorizada e paralelizada**. O **alinhamento de memória** (C-contíguo vs Fortran-contíguo) afeta a **eficiência do acesso sequencial**, impactando diretamente a performance dessas operações.

---

### **Analogia do Dia**

Imagine que você quer **somar todos os valores de uma planilha**.
Com `for`, é como usar uma **calculadora linha por linha**.
Com `ufuncs`, você chama um **robô industrial** que lê a planilha inteira de uma vez — **muito mais rápido** se os dados estiverem bem **organizados em linha ou em coluna**, como o robô espera.

---

### **Análise Técnica Detalhada**

---

#### 🧠 1. O que são **ufuncs** (universal functions)

```python
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

c = a + b         # ufunc vetorizada: np.add(a, b)
d = np.sqrt(c)    # ufunc unária: np.sqrt(c)
```

* Ufuncs são **funções elementares otimizadas** da NumPy
* Escritas em **C**, são:

  * **rapidamente aplicadas** a arrays inteiros
  * **paralelizadas** em alguns casos
  * Sem laços Python = sem overhead

---

#### 📉 2. O que são **reduções**

```python
a = np.arange(1_000_000)

soma = a.sum()     # np.sum(a)
media = a.mean()   # np.mean(a)
```

* Reduções são **operações agregadoras**
* Internamente, são feitas com **blocos de memória contígua**
* **Muito mais rápidas** que:

```python
total = 0
for x in a:
    total += x
```

---

#### ⚙️ 3. Impacto do **layout de memória**

```python
a = np.ones((10000, 100), order="C")  # linha por linha
b = np.ones((10000, 100), order="F")  # coluna por coluna
```

* **C-contíguo** (row-major): ideal para reduções por linha (eixo 1)
* **Fortran-contíguo** (column-major): ideal para reduções por coluna (eixo 0)

🔁 Se os dados não estiverem no layout correto:

* Ufuncs e reduções **ainda funcionam**, mas
* NumPy pode ter que **realocar ou reordenar** internamente (mais lento!)

---

### **Nota de Rodapé para Novatos**

* **Ufunc (universal function)**: Função NumPy otimizada para operar em arrays inteiros.
* **Redução**: Operação que **resume** um array (como soma, média, máx).
* **Overhead**: Tempo/memória extra que Python consome com loops.
* **C-contíguo**: Dados armazenados linha por linha.
* **Fortran-contíguo**: Dados armazenados coluna por coluna.
* **`order="C"` / `"F"`**: Define o layout ao criar arrays NumPy.

---

### **Aplicação Prática e Boas Práticas**

✅ Use ufuncs e reduções para:

* Cálculos estatísticos: `np.mean`, `np.std`, `np.max`
* Operações elementares: `np.exp`, `np.log`, `np.clip`, etc.
* **Substituir loops** e acelerar pipelines de dados

💡 Boas práticas:

* Verifique se o array é contíguo com:

```python
a.flags['C_CONTIGUOUS']  # ou 'F_CONTIGUOUS'
```

* Use `np.ascontiguousarray()` se precisar forçar otimização:

```python
a = np.ascontiguousarray(a)
```

⚡ Em ML/DL:

* Operações com `np.dot`, `@`, `np.matmul` e `np.sum(axis=...)` são **cruciais**
* Bibliotecas como **TensorFlow e PyTorch** se baseiam nessas ideias

---

### **Resumo da Lição**

**Ufuncs e reduções eliminam loops Python**, operando de forma vetorizada e ultraeficiente. Para extrair **o máximo de performance**, é essencial que o **layout de memória esteja alinhado** ao tipo de operação — um detalhe que pode fazer toda a diferença em grandes datasets.

---

Se quiser, posso mostrar um comparativo de tempo real entre `for` e `np.sum()`. Quer ver na prática a diferença brutal? 🕒⚡
